- type: job
  parent: RMCJobRibbonBase
  id: SVXJobPatreon
  name: svx-job-name-patreon
  description: Patreon perks
  playTimeTracker: SVXJobPatreon
  basePlaytimeTracker: true
  hidden: true

- type: playTimeTracker
  id: SVXJobPatreon
  name: svx-job-name-patreon
  isHumanoid: true