- type: playTimeTracker
  id: SVXJobMonkeyXeno
  isXeno: true

- type: entity
  parent: [RMCBaseMobSpeciesOrganic]
  id: SVXMonkeyXenoHost
  name: monkey (SVX xeno host)
  suffix: svx, Monkey host
  components:
  - type: FireVisuals
    sprite: Mobs/Effects/onfire.rsi
    normalState: Monkey_burning
    alternateState: Monkey_burning
    fireStackAlternateState: 14
    lightRadiusPerStack: 0.2
    maxLightRadius: 3
  - type: HumanoidAppearance
    species: svxmonkey
  - type: Speech
    speechSounds: Monkey
    speechVerb: Monkey
  - type: MonkeyAccent
  - type: Tag
    tags:
      - SubdermalImplant
      - FootstepSound
      - DoorBumpOpener

- type: entity
  parent: SVXMonkeyXenoHost
  id: SVXMonkeyXenoBase
  name: monkey (SVX xeno base)
  components:
  - type: UserInterface
    interfaces:
      enum.SVXMonkeyCasteUIKey.Key:
        type: SVXMonkeyCasteBui
      enum.TacticalMapUserUi.Key:
        type: TacticalMapUserBui
  - type: SVXMonkey
  - type: Skills
    preset: RMCSkillPresetSurvivor
  - type: SVXMonkeyLoadout
  - type: UserIFF
    factions:
    - FactionMonkey
  - type: TacticalMapUser
    marines: true
    xenos: true
    canDraw: false
    liveUpdate: true
    actionId: RMCActionOpenTacticalMapMarine
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: forecon_synth

