using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._SVX.Monkey;

[GenerateTypedNameReferences]
public sealed partial class SVXMonkeyCasteWindow : DefaultWindow
{
    public SVXMonkeyCasteWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
