- type: job
  parent: RMCSurvivorPMCBase
  id: SVXSurvivorSpaceshipPMCCommander
  name: rmc-job-name-pmc-field-operations-leader
  whitelistParent: CMCommandingOfficer
  ranks:
    RMCRankWeYaFieldOperaionsLeader: []
  supervisors: cm-job-supervisors-we-ya
  accessGroups:
  - ColonistPMC
  startingGear: SVXGearSurvivorPMCCommander
  icon: SVXJobIconPMCCommander
  greeting: rmc-job-greeting-solaris-pmc-commander
  playTimeTracker: RMCJobSurvivorCO
  spawnMenuRoleName: PMC Field Operations Leader (Solaris Special Survivor)
  special:
  - !type:AddComponentSpecial
    components:
    - type: Language
      spokenLanguages:
      - Japanese
      - English
      understoodLanguages:
      - Japanese
      - English
      currentLanguage: English
      defaultLanguage: English
    - type: Skills
      preset: RMCSkillPresetSurvivorWeYaPMCCommander
    - type: MarineOrders
    - type: RMCPointing
    - type: CommandAccent
    - type: InnateCommandSpeech
    - type: RMCSurvivor
    - type: MotionDetectorTracked
    - type: RMCAllowSuitStorage
    - type: IntelRescueSurvivorObjective
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetNoGun
    - type: NpcFactionMember
      factions:
      - SvX
      - Civilian
    - type: AssignSquad
      squad: SquadPMC
    - type: JobPrefix
      prefix: rmc-job-prefix-pmc-leader
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: pmc_sd
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_pmc
  useLoadoutOfJob: RMCSurvivorCommandingOfficer

- type: startingGear
  parent: RMCGearSurvivorPMCBase
  id: SVXGearSurvivorPMCCommander
  equipment:
    jumpsuit: RMCJumpsuitVeteranPMCLeaderHolsterPatch
    shoes: RMCBootsPMCFilled
    gloves: RMCHandsVeteranPMC
    ears: RMCHeadsetHvHWeYaPMCLeader
    outerClothing: SVXArmorSVXM24
    back: RMCBackpackRTOPMCBroken
    belt: SVXBeltEnergyStandard
    pocket1: RMCPouchSurvivalBlackFilled
    pocket2: RMCPouchMedkitPMCFullAdvanced
  storage:
    back:
    - CMSheetMetal20
    - CMSheetPlasteel20
    - RMCAttachmentFlashlightGrip
    - RMCAttachmentS6ReflexSight
    # TODO RMC14: Crew monitor
    outerClothing:
    - RMCMREWeYa
    - RMCRangefinder
  inhand:
  - SVXWeaponAlienRifle

- type: entity
  parent: CMSpawnPointJobBase
  id: SVXSpawnPointSurvivorCrashlandingOfficesFOL
  name: special survivor crashlanding offices pmc field operations leader spawn point
  components:
  - type: SpawnPoint
    job_id: SVXSurvivorSpaceshipPMCCommander
  - type: Sprite
    layers:
    - sprite: _RMC14/Markers/landmarks.rsi
      state: surv_wy

- type: jobIcon
  parent: CMJobIconBase
  id: SVXJobIconPMCCommander
  icon:
    sprite: _RMC14/Interface/job_icons/We-Ya/pmc.rsi
    state: pmc_fol
