- type: department
  parent: CMDepartmentBase
  id: CMEngineering
  name: department-CMEngineering
  description: cm-department-Engineering-description
  color: "#A66300"
  hidden: true
  roles:
  - CMChiefEngineer
  - CMOrdnanceTech
  - CMMaintTech
  departmentRadio: MarineEngineer
  headOfDepartment: CMChiefEngineer
